from __future__ import annotations

import hashlib
from pathlib import Path
from typing import Any

from .receipts import emit_projection_receipt


PORTABLE_HARNESS_PLUGIN_ID = "portable-harness-projection"
PORTABLE_HARNESS_PLUGIN_VERSION = "0.1.0"


def render_agents_md(
    *,
    workstream_payload: dict[str, Any],
    memory_payloads: list[dict[str, Any]],
    compiled_state_payload: dict[str, Any] | None = None,
    selected_context_slices: list[dict[str, Any]] | None = None,
) -> str:
    scope = workstream_payload.get("scope", {})
    task_labels = workstream_payload.get("task_labels", [])
    recurring_terms = workstream_payload.get("recurring_terms", [])
    source_refs = workstream_payload.get("source_refs", [])
    notes = workstream_payload.get("notes")

    lines = [
        "# AGENTS.md",
        "",
        "<!-- Generated by CtxVault. Treat this file as a projection, not canonical truth. -->",
        "",
        "## Active Workstream",
        "",
        f"- ID: `{workstream_payload['id']}`",
        f"- Title: {workstream_payload['title']}",
        f"- Scope: `{scope.get('kind', 'unknown')}:{scope.get('value', 'unknown')}`",
        f"- Status: `{workstream_payload.get('status', 'active')}`",
        f"- Summary: {workstream_payload.get('summary') or 'No summary available.'}",
    ]

    if task_labels:
        lines.extend(
            [
                "",
                "## Current Tasks",
                "",
                *[f"- {label}" for label in task_labels],
            ]
        )

    if recurring_terms:
        lines.extend(
            [
                "",
                "## Recurring Terms",
                "",
                f"- {', '.join(str(term) for term in recurring_terms)}",
            ]
        )

    lines.extend(_compiled_state_lines(compiled_state_payload, heading="Compiled Workstream State"))
    lines.extend(_selected_context_slice_lines(selected_context_slices))

    lines.extend(["", "## Durable Operating Rules", ""])
    if memory_payloads:
        for memory in memory_payloads:
            lines.append(f"- {memory.get('statement') or memory['id']}")
    else:
        lines.append("- No approved portable rules were selected.")

    if notes:
        lines.extend(
            [
                "",
                "## Maintainer Notes",
                "",
                str(notes),
            ]
        )

    if source_refs:
        lines.extend(
            [
                "",
                "## Source Refs",
                "",
                *[f"- `{ref}`" for ref in source_refs],
            ]
        )

    return "\n".join(lines).rstrip() + "\n"


def render_claude_md(
    *,
    workstream_payload: dict[str, Any],
    memory_payloads: list[dict[str, Any]],
    compiled_state_payload: dict[str, Any] | None = None,
    selected_context_slices: list[dict[str, Any]] | None = None,
) -> str:
    scope = workstream_payload.get("scope", {})
    task_labels = workstream_payload.get("task_labels", [])
    recurring_terms = workstream_payload.get("recurring_terms", [])
    source_refs = workstream_payload.get("source_refs", [])
    notes = workstream_payload.get("notes")

    lines = [
        "# CLAUDE.md",
        "",
        "<!-- Generated by CtxVault. Treat this file as a projection, not canonical truth. -->",
        "",
        "## Project Context",
        "",
        f"- Workstream ID: `{workstream_payload['id']}`",
        f"- Title: {workstream_payload['title']}",
        f"- Scope: `{scope.get('kind', 'unknown')}:{scope.get('value', 'unknown')}`",
        f"- Status: `{workstream_payload.get('status', 'active')}`",
        f"- Summary: {workstream_payload.get('summary') or 'No summary available.'}",
    ]

    if task_labels:
        lines.extend(
            [
                "",
                "## Current Tasks",
                "",
                *[f"- {label}" for label in task_labels],
            ]
        )

    if recurring_terms:
        lines.extend(
            [
                "",
                "## Focus Terms",
                "",
                f"- {', '.join(str(term) for term in recurring_terms)}",
            ]
        )

    lines.extend(_compiled_state_lines(compiled_state_payload, heading="Compiled Workstream State"))
    lines.extend(_selected_context_slice_lines(selected_context_slices))

    lines.extend(["", "## Durable Rules", ""])
    if memory_payloads:
        for memory in memory_payloads:
            lines.append(f"- {memory.get('statement') or memory['id']}")
    else:
        lines.append("- No approved portable rules were selected.")

    if notes:
        lines.extend(
            [
                "",
                "## Maintainer Notes",
                "",
                str(notes),
            ]
        )

    if source_refs:
        lines.extend(
            [
                "",
                "## Source Refs",
                "",
                *[f"- `{ref}`" for ref in source_refs],
            ]
        )

    return "\n".join(lines).rstrip() + "\n"


def render_wiki_workstream_md(
    *,
    workstream_payload: dict[str, Any],
    memory_payloads: list[dict[str, Any]],
    compiled_state_payload: dict[str, Any] | None = None,
    selected_context_slices: list[dict[str, Any]] | None = None,
) -> str:
    scope = workstream_payload.get("scope", {})
    task_labels = workstream_payload.get("task_labels", [])
    recurring_terms = workstream_payload.get("recurring_terms", [])
    source_refs = workstream_payload.get("source_refs", [])
    notes = workstream_payload.get("notes")

    lines = [
        f"# {workstream_payload['title']}",
        "",
        "> Generated by CtxVault. Treat this note as a projection, not canonical truth.",
        "",
        "## Workstream",
        "",
        f"- ID: `{workstream_payload['id']}`",
        f"- Scope: `{scope.get('kind', 'unknown')}:{scope.get('value', 'unknown')}`",
        f"- Status: `{workstream_payload.get('status', 'active')}`",
        f"- Summary: {workstream_payload.get('summary') or 'No summary available.'}",
    ]

    if task_labels:
        lines.extend(
            [
                "",
                "## Current Tasks",
                "",
                *[f"- {label}" for label in task_labels],
            ]
        )

    if recurring_terms:
        lines.extend(
            [
                "",
                "## Recurring Terms",
                "",
                f"- {', '.join(str(term) for term in recurring_terms)}",
            ]
        )

    lines.extend(_compiled_state_lines(compiled_state_payload, heading="Current Truth"))
    lines.extend(_selected_context_slice_lines(selected_context_slices))

    lines.extend(["", "## Durable Rules", ""])
    if memory_payloads:
        for memory in memory_payloads:
            lines.append(f"- {memory.get('statement') or memory['id']}")
    else:
        lines.append("- No approved portable rules were selected.")

    if notes:
        lines.extend(
            [
                "",
                "## Maintainer Notes",
                "",
                str(notes),
            ]
        )

    if source_refs:
        lines.extend(
            [
                "",
                "## Source Refs",
                "",
                *[f"- `{ref}`" for ref in source_refs],
            ]
        )

    return "\n".join(lines).rstrip() + "\n"


def _compiled_state_lines(compiled_state_payload: dict[str, Any] | None, *, heading: str) -> list[str]:
    if not compiled_state_payload:
        return []
    current_truth = dict(compiled_state_payload.get("current_truth") or {})
    summary = dict(current_truth.get("summary") or {})
    lines = ["", f"## {heading}", ""]
    summary_text = str(summary.get("text") or "").strip()
    if summary_text:
        lines.append(f"- Summary: {summary_text}")
    for label, key in [
        ("Decisions", "active_decisions"),
        ("Constraints", "active_constraints"),
        ("Open Questions", "open_questions"),
        ("Next Actions", "next_actions"),
        ("Reusable Judgments", "reusable_judgments"),
    ]:
        items = [
            str(item.get("text") or "").strip()
            for item in list(current_truth.get(key) or [])
            if isinstance(item, dict) and str(item.get("text") or "").strip()
        ]
        if not items:
            continue
        lines.extend(["", f"### {label}", "", *[f"- {item}" for item in items]])
    source_refs = [
        str(ref).strip()
        for ref in list(compiled_state_payload.get("source_refs") or [])
        if str(ref).strip()
    ][:8]
    if source_refs:
        lines.extend(["", "### Compiled Source Refs", "", *[f"- `{ref}`" for ref in source_refs]])
    warnings = [
        str(warning).strip()
        for warning in list(compiled_state_payload.get("warnings") or [])
        if str(warning).strip()
    ]
    if warnings:
        lines.extend(["", "### Advisory Warnings", "", *[f"- {warning}" for warning in warnings]])
    return lines


def _selected_context_slice_lines(selected_context_slices: list[dict[str, Any]] | None) -> list[str]:
    if not selected_context_slices:
        return []
    lines = ["", "## Selected Context Slices", ""]
    for item in selected_context_slices:
        slice_ref = str(item.get("slice_ref") or "").strip()
        source_ref = str(item.get("source_ref") or "").strip()
        title = str(item.get("title") or slice_ref or "Selected slice").strip()
        preview = str(item.get("redacted_preview") or "").strip()
        privacy_class = str(item.get("privacy_class") or "unknown").strip()
        lines.append(f"- {title}")
        if slice_ref:
            lines.append(f"  - Slice: `{slice_ref}`")
        if source_ref:
            lines.append(f"  - Source: `{source_ref}`")
        lines.append(f"  - Privacy: `{privacy_class}`")
        if preview:
            lines.append(f"  - Preview: {preview}")
        else:
            lines.append("  - Preview: [metadata only]")
    return lines


def emit_agents_md_projection(
    *,
    root: Path,
    output_path: Path,
    receipt_output_path: Path,
    workstream_payload: dict[str, Any],
    memory_payloads: list[dict[str, Any]],
    compiled_state_payload: dict[str, Any] | None = None,
    selected_context_slices: list[dict[str, Any]] | None = None,
    privacy_preflight: dict[str, Any] | None = None,
) -> dict[str, Any]:
    rendered = render_agents_md(
        workstream_payload=workstream_payload,
        memory_payloads=memory_payloads,
        compiled_state_payload=compiled_state_payload,
        selected_context_slices=selected_context_slices,
    )
    resolved_output = output_path.resolve()
    resolved_output.parent.mkdir(parents=True, exist_ok=True)
    resolved_output.write_text(rendered, encoding="utf-8")
    output_bytes = rendered.encode("utf-8")
    output_sha256 = hashlib.sha256(output_bytes).hexdigest()
    workstream_ref = f"workstream://{workstream_payload['id']}"
    memory_refs = [f"memory://{memory['id']}" for memory in memory_payloads]
    selected_slice_refs = _selected_slice_refs(selected_context_slices)

    receipt_payload = {
        "receipt_id": f"projection_receipt_{workstream_payload['id']}_agents_md",
        "projection_id": f"{workstream_payload['id']}_agents_md",
        "projection_kind": "harness",
        "target_kind": "harness.agents-md",
        "target_path": str(resolved_output),
        "source_refs": [workstream_ref, *memory_refs, *selected_slice_refs],
        "source_object_kinds": ["Workstream", *(["Memory"] if memory_payloads else []), *(["ContextSlice"] if selected_slice_refs else [])],
        "scope": dict(workstream_payload["scope"]),
        "plugin_id": PORTABLE_HARNESS_PLUGIN_ID,
        "plugin_version": PORTABLE_HARNESS_PLUGIN_VERSION,
        "render_policy": "density-first",
        "merge_policy": "replace",
        "output_sha256": output_sha256,
        "output_bytes": len(output_bytes),
        "output_status": "written",
        "policy_decision": "allow",
        "review_state": _projection_review_state(workstream_payload),
        "warnings": [],
        "selected_slice_refs": selected_slice_refs,
        "privacy_preflight": privacy_preflight,
    }
    receipt = emit_projection_receipt(
        root=root,
        output_path=receipt_output_path,
        projection_payload=receipt_payload,
    )
    return {
        "projection_id": receipt_payload["projection_id"],
        "output_path": str(resolved_output),
        "receipt_path": receipt["receipt_path"],
        "receipt": receipt["receipt"],
        "workstream": {
            "id": workstream_payload["id"],
            "title": workstream_payload["title"],
        },
        "memory_count": len(memory_payloads),
        "source_refs": receipt_payload["source_refs"],
    }


def emit_claude_md_projection(
    *,
    root: Path,
    output_path: Path,
    receipt_output_path: Path,
    workstream_payload: dict[str, Any],
    memory_payloads: list[dict[str, Any]],
    compiled_state_payload: dict[str, Any] | None = None,
    selected_context_slices: list[dict[str, Any]] | None = None,
    privacy_preflight: dict[str, Any] | None = None,
) -> dict[str, Any]:
    rendered = render_claude_md(
        workstream_payload=workstream_payload,
        memory_payloads=memory_payloads,
        compiled_state_payload=compiled_state_payload,
        selected_context_slices=selected_context_slices,
    )
    resolved_output = output_path.resolve()
    resolved_output.parent.mkdir(parents=True, exist_ok=True)
    resolved_output.write_text(rendered, encoding="utf-8")
    output_bytes = rendered.encode("utf-8")
    output_sha256 = hashlib.sha256(output_bytes).hexdigest()
    workstream_ref = f"workstream://{workstream_payload['id']}"
    memory_refs = [f"memory://{memory['id']}" for memory in memory_payloads]
    selected_slice_refs = _selected_slice_refs(selected_context_slices)

    receipt_payload = {
        "receipt_id": f"projection_receipt_{workstream_payload['id']}_claude_md",
        "projection_id": f"{workstream_payload['id']}_claude_md",
        "projection_kind": "harness",
        "target_kind": "harness.claude-md",
        "target_path": str(resolved_output),
        "source_refs": [workstream_ref, *memory_refs, *selected_slice_refs],
        "source_object_kinds": ["Workstream", *(["Memory"] if memory_payloads else []), *(["ContextSlice"] if selected_slice_refs else [])],
        "scope": dict(workstream_payload["scope"]),
        "plugin_id": PORTABLE_HARNESS_PLUGIN_ID,
        "plugin_version": PORTABLE_HARNESS_PLUGIN_VERSION,
        "render_policy": "density-first",
        "merge_policy": "replace",
        "output_sha256": output_sha256,
        "output_bytes": len(output_bytes),
        "output_status": "written",
        "policy_decision": "allow",
        "review_state": _projection_review_state(workstream_payload),
        "warnings": [],
        "selected_slice_refs": selected_slice_refs,
        "privacy_preflight": privacy_preflight,
    }
    receipt = emit_projection_receipt(
        root=root,
        output_path=receipt_output_path,
        projection_payload=receipt_payload,
    )
    return {
        "projection_id": receipt_payload["projection_id"],
        "output_path": str(resolved_output),
        "receipt_path": receipt["receipt_path"],
        "receipt": receipt["receipt"],
        "workstream": {
            "id": workstream_payload["id"],
            "title": workstream_payload["title"],
        },
        "memory_count": len(memory_payloads),
        "source_refs": receipt_payload["source_refs"],
    }


def emit_wiki_workstream_md_projection(
    *,
    root: Path,
    output_path: Path,
    receipt_output_path: Path,
    workstream_payload: dict[str, Any],
    memory_payloads: list[dict[str, Any]],
    compiled_state_payload: dict[str, Any] | None = None,
    selected_context_slices: list[dict[str, Any]] | None = None,
    privacy_preflight: dict[str, Any] | None = None,
) -> dict[str, Any]:
    rendered = render_wiki_workstream_md(
        workstream_payload=workstream_payload,
        memory_payloads=memory_payloads,
        compiled_state_payload=compiled_state_payload,
        selected_context_slices=selected_context_slices,
    )
    resolved_output = output_path.resolve()
    resolved_output.parent.mkdir(parents=True, exist_ok=True)
    resolved_output.write_text(rendered, encoding="utf-8")
    output_bytes = rendered.encode("utf-8")
    output_sha256 = hashlib.sha256(output_bytes).hexdigest()
    workstream_ref = f"workstream://{workstream_payload['id']}"
    memory_refs = [f"memory://{memory['id']}" for memory in memory_payloads]
    selected_slice_refs = _selected_slice_refs(selected_context_slices)

    receipt_payload = {
        "receipt_id": f"projection_receipt_{workstream_payload['id']}_wiki_md",
        "projection_id": f"{workstream_payload['id']}_wiki_md",
        "projection_kind": "wiki",
        "target_kind": "wiki.markdown-workstream",
        "target_path": str(resolved_output),
        "source_refs": [workstream_ref, *memory_refs, *selected_slice_refs],
        "source_object_kinds": ["Workstream", *(["Memory"] if memory_payloads else []), *(["ContextSlice"] if selected_slice_refs else [])],
        "scope": dict(workstream_payload["scope"]),
        "plugin_id": PORTABLE_HARNESS_PLUGIN_ID,
        "plugin_version": PORTABLE_HARNESS_PLUGIN_VERSION,
        "render_policy": "density-first",
        "merge_policy": "replace",
        "output_sha256": output_sha256,
        "output_bytes": len(output_bytes),
        "output_status": "written",
        "policy_decision": "allow",
        "review_state": _projection_review_state(workstream_payload),
        "warnings": [],
        "selected_slice_refs": selected_slice_refs,
        "privacy_preflight": privacy_preflight,
    }
    receipt = emit_projection_receipt(
        root=root,
        output_path=receipt_output_path,
        projection_payload=receipt_payload,
    )
    return {
        "projection_id": receipt_payload["projection_id"],
        "output_path": str(resolved_output),
        "receipt_path": receipt["receipt_path"],
        "receipt": receipt["receipt"],
        "workstream": {
            "id": workstream_payload["id"],
            "title": workstream_payload["title"],
        },
        "memory_count": len(memory_payloads),
        "source_refs": receipt_payload["source_refs"],
    }


def _projection_review_state(workstream_payload: dict[str, Any]) -> str:
    return str(workstream_payload.get("approval_state") or "generated")


def _selected_slice_refs(selected_context_slices: list[dict[str, Any]] | None) -> list[str]:
    return [
        str(item.get("slice_ref")).strip()
        for item in selected_context_slices or []
        if str(item.get("slice_ref") or "").strip()
    ]
